<?php

use App\Listeners\MailListener;
use App\Subjects\BulletinBoard;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-03-04 at 23:31:55.
 */
class BulletinBoardTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var BulletinBoard
     */
    protected $bulletinBoard;

    /**
     *
     * @var PHPUnit_Framework_MockObject_MockObject
     */
    protected $mailListener;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->bulletinBoard = new BulletinBoard('テスト太郎');
        $this->mailListener = new MailListener();
        $this->bulletinBoard->addObserver($this->mailListener);

        $this->bulletinBoard->comment('テストテキスト');
     // $this->mailListener = $this->getMockBuilder(MailListener::class)->getMock();
    }

    /**
     * @covers App\Subjects\BulletinBoard::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Subjects\BulletinBoard::comment
     * @todo   Implement testComment().
     */
    public function testComment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Subjects\BulletinBoard::addComment
     * @todo   Implement testAddComment().
     */
    public function testAddComment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Subjects\BulletinBoard::processComment
     * @todo   Implement testProcessComment().
     */
    public function testProcessComment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }


    /**
     * @covers App\Subjects\BulletinBoard::addObserver
     * @todo   Implement testAddObserver().
     */
    public function testAddObserver()
    {
        $this->mailListener->expects($this->once())->method('execute')->willReturn('メール送信したよ');
        $this->bulletinBoard->addObserver($this->mailListener);
        var_dump($this->bulletinBoard->notify());
    }

    /**
     * @covers App\Subjects\BulletinBoard::removeObserver
     * @todo   Implement testRemoveObserver().
     */
    public function testRemoveObserver()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Subjects\BulletinBoard::notify
     * @todo   Implement testNotify().
     */
    public function testNotify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
