<?php

use App\Item\MachineModel;
use App\Item\PartsCpu;
use App\Management\Choose;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-05-02 at 16:32:19.
 */
class ChooseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Choose
     */
    protected $choose;

    /**
     * クラスを呼び出し用のID
     * @var int
     */
    private const ID_01 = 1;
    private const ID_02 = 2;

    protected function setUp()
    {
        $this->choose = new Choose;
    }

    /**
     * @test
     */
    public function testAdd()
    {
        $machine_model = new MachineModel();
        $machine_model_1 = $machine_model->getItem(self::ID_01);

        $parts_cpu = new PartsCpu();
        $parts_cpu_1 = $parts_cpu->getItem(self::ID_02);

        $this->choose->add($machine_model_1);
        $this->choose->add($parts_cpu_1);

        $expect_item_array[] = $machine_model->getItem(self::ID_01);
        $expect_item_array[] = $parts_cpu->getItem(self::ID_02);

        $chooses = $this->choose->getChooses();

        $this->assertEquals($expect_item_array[0], $chooses[0]);
        $this->assertEquals($expect_item_array[1], $chooses[1]);
    }
}
