<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-03-09 at 23:04:55.
 */
class DollarExchangeTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DollarExchange
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DollarExchange;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers App\Exchange\DollarExchange::currencyConversion
     * @todo   Implement testCurrencyConversion().
     */
    public function testCurrencyConversion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
