<?php

use App\Listeners\LoggingListener;
use App\Listeners\MailListener;
use App\Listeners\SlackListener;
use App\Subjects\BulletinBoard;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-03-07 at 18:14:05.
 */
class ListenerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var  BulletinBoard
     */
    protected $bulletinBoard;

    /**
     * @var SlackListener
     */
    protected $slackListener;

    /**
     * @var MailListener
     */
    protected $mailListener;

    /**
     * @var LoggingListener
     */
    protected $loggingListener;

    public function setUp()
    {
        $this->bulletinBoard = new BulletinBoard('テスト太郎');
        $this->slackListener = new SlackListener();
        $this->mailListener = new MailListener();
        $this->loggingListener = new LoggingListener();
    }

    /**
     * スラックに通知されるかどうかテスト
     * @test
     *
     */
    public function testSlackListener()
    {
        $this->assertSame('スラック通知したよ',$this->slackListener->execute($this->bulletinBoard));
    }

    /**
     * メールが送信されるかどうかテスト
     * @test
     *
     */
    public function testMailListener()
    {
        $this->assertSame('メール送信したよ',$this->mailListener->execute($this->bulletinBoard));
    }

    /**
     * ログに残るかどうかテスト
     * @test
     *
     */
    public function testLoggingListener()
    {
        $this->assertSame('ログ書き込みOK',$this->loggingListener->execute($this->bulletinBoard));
    }
}
