<?php

use App\Components\TravelPlan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-02-29 at 14:37:53.
 */
class TravlePlanTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var TravelPlan
     */
    protected $object;

    private $plan;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TravelPlan;
        $this->object->setPlan("旅行テスト");
        $this->object->setCost(1000);
        $this->object->setDuration('9/12~10/12');
    }

    /**
     * @covers App\Components\TravelPlan::getPlan
     * @todo   Implement testGetPlan().
     */
    public function testGetPlan()
    {
        $this->assertEquals('旅行テスト', $this->object->getPlan());
    }

    /**
     * @covers App\Components\TravelPlan::getCost
     * @todo   Implement testGetCost().
     */
    public function testGetCost()
    {
        $this->assertEquals(1000, $this->object->getCost());
    }

    /**
     * @covers App\Components\TravelPlan::getDuration
     * @todo   Implement testGetDuration().
     */
    public function testGetDuration()
    {
        $this->assertEquals('9/12~10/12', $this->object->getDuration());
    }
}
