<?php

use App\Components\TravelPlan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-02-29 at 14:37:53.
 */
class TravelPlanTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var TravelPlan
     */
    protected $travelPlan;

    protected function setUp()
    {
        $this->travelPlan = new TravelPlan;
        $this->travelPlan->setPlan("旅行テスト");
        $this->travelPlan->setCost(1000);
        $this->travelPlan->setDuration('9/12~10/12');
    }

    /**
     * @test
     *
     */
    public function testGetPlan()
    {
        $this->assertEquals('旅行テスト', $this->travelPlan->getPlan());
    }

    /**
     * @test
     *
     */
    public function testGetCost()
    {
        $this->assertEquals(1000, $this->travelPlan->getCost());
    }

    /**
     * @test
     *
     */
    public function testGetDuration()
    {
        $this->assertEquals('9/12~10/12', $this->travelPlan->getDuration());
    }
}
