<?php

use App\Components\TravelPlan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-02-29 at 14:37:53.
 */
class TravelPlanTestPlanTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var TravelPlan
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new TravelPlan;
        $this->object->setPlan("旅行テスト");
        $this->object->setCost(1000);
        $this->object->setDuration('9/12~10/12');
    }

    /**
     * @test
     *
     */
    public function testGetPlan()
    {
        $this->assertEquals('旅行テスト', $this->object->getPlan());
    }

    /**
     * @test
     *
     */
    public function testGetCost()
    {
        $this->assertEquals(1000, $this->object->getCost());
    }

    /**
     * @test
     *
     */
    public function testGetDuration()
    {
        $this->assertEquals('9/12~10/12', $this->object->getDuration());
    }
}
