<?php

use App\Components\TravelPlan;
use App\Decorators\Packs\AirplanePack;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-02-29 at 15:35:48.
 */
class AirplanePackTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var TravelPlan
     */
    private $travelPlan;
    
    /**
     * @var AirplanePack
     */
    private $airplanePack;
    
    protected function setUp()
    {
        $travelPlan = new TravelPlan();
        $travelPlan->setPlan("旅行テスト");
        $this->airplanePack = new AirplanePack($travelPlan,"飛行機テスト",3000);
    }
    
    /**
     * @test
     * 
     */
    public function testGetPlan()
    {
        $this->assertEquals('旅行テスト /飛行機パック (飛行機テスト)',$this->airplanePack->getPlan());
    }

    /**
     * @test
     *
     */
    public function testGetCost()
    {
        $this->assertEquals(3000,$this->airplanePack->getCost());
    }
}
