<?php

use App\Components\TravelPlan;
use App\Decorators\Packs\AirplanePack;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-02-29 at 15:35:48.
 */
class AirplanePackTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var AirplanePack
     */
    protected $object;

    protected function setUp()
    {
        $plan_base = new TravelPlan();
        $plan_base->setPlan("旅行テスト");
        $this->object = new AirplanePack($plan_base, "飛行機テスト", 3000);
    }

    /**
     * @test
     *
     */
    public function testGetPlan()
    {
        $this->assertEquals('旅行テスト /飛行機パック (飛行機テスト)', $this->object->getPlan());
    }

    /**
     * @test
     *
     */
    public function testGetCost()
    {
        $this->assertEquals(3000, $this->object->getCost());
    }
}

