<?php

use App\Components\TravelPlan;
use App\Decorators\Packs\HotelPack;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-02-29 at 16:09:26.
 */
class HotelPackTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var TravelPlan
     */
    private $travelPlan;
    
    /**
     * @var HotelPack
     */
    protected $hotelPack;

    protected function setUp()
    {
        $travelPlan = new TravelPlan();
        $travelPlan->setPlan('旅行テスト');
        $this->hotelPack = new HotelPack($travelPlan, 'ホテルテスト', 1000);
    }

    /**
     * @test
     *
     */
    public function testGetPlan()
    {
        $this->assertThat($this->hotelPack->getPlan(), $this->equalTo('旅行テスト / ホテルパック (ホテルテスト)'));
    }

    /**
     * @test
     *
     */
    public function testGetCost()
    {
        $this->assertEquals(1000, $this->hotelPack->getCost());
    }
}
