<?php

namespace Tests\Feature\Listeners;

use App\Listeners\LoggingListener;
use App\Subjects\BulletinBoard;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-03-07 at 18:14:05.
 */
class LoggingListenerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var  BulletinBoard
     */
    protected $bulletinBoard;

    /**
     * @var LoggingListener
     */
    protected $loggingListener;

    public function setUp()
    {
        $this->bulletinBoard = new BulletinBoard('テスト太郎');
        $this->loggingListener = new LoggingListener();
    }

    /**
     * ログに残るかどうかテスト
     * @test
     *
     */
    public function testLoggingListener()
    {
        $this->assertSame('ログ書き込みOK',$this->loggingListener->execute($this->bulletinBoard));
    }
}
