<?php

namespace Tests\Feature\Listener;

use App\Subjects\BulletinBoard;
use App\Listeners\MailListener;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-03-07 at 18:14:05.
 */
class MailListenerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var  BulletinBoard
     */
    protected $bulletinBoard;

    /**
     * @var MailListener
     */
    protected $mailListener;


    public function setUp()
    {
        $this->bulletinBoard = new BulletinBoard('テスト太郎');
        $this->mailListener = new MailListener();
    }

    /**
     * メールが送信されるかどうかテスト
     * @test
     *
     */
    public function testMailListener()
    {
        $this->assertSame('メール送信したよ', $this->mailListener->execute($this->bulletinBoard));
    }
}
