<?php

namespace Tests\Feature\Listener;

use App\Subjects\BulletinBoard;
use App\Listeners\SlackListener;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-03-07 at 18:14:05.
 */
class SlackListenerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var  BulletinBoard
     */
    protected $bulletinBoard;

    /**
     * @var SlackListener
     */
    protected $slackListener;

    public function setUp()
    {
        $this->bulletinBoard = new BulletinBoard('テスト太郎');
        $this->slackListener = new SlackListener();
    }

    /**
     * スラックに通知されるかどうかテスト
     * @test
     *
     */
    public function testSlackListener()
    {
        $this->assertSame('スラック通知したよ',$this->slackListener->execute($this->bulletinBoard));
    }
}
